### ISSUE TITLE
Add --retry option for autify web test run

### ISSUE THREAD

**Issue by meih** [autifyhq/autify-cli#102]
In some cases, Autify users want to automatically retry specific tests a limited number of times (once or twice) until it passes. If Autify CLI can support this (with `--retry` option along with `--wait` option), that would be great.

**Comment by riywo** [comment]
@meih Thank you for the feature request. We released `--max-retry-count` in `beta` channel. Feel free to try it out and give us any feedback! https://github.com/autifyhq/autify-cli/pull/104

```
autify update beta
autify web test run --wait --max-retry-count 2
```

**Comment by meih** [comment]
Cool!  Thanks for implementing this so quickly.
